#!/usr/bin/env bash
#Prints 'bad luck from China' on the 4th operation
#Prints 'bad luck from Japan' on the 9th opreration
#prints 'bad luck from Italy ' on the 17th operation
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		4) echo "bad luck from China"
			;;
		9) echo "bad luk from Japan"
			;;
		17) echo "bad luck from Italy"
			;;
	esac
	(( i++ ))
done
		
