#!/usr/bin/env bash
#displays hours from 0 to 12
#displays minutes fro 1 to 59
#all using while loop
hour=0
min=1
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	while [ $min -le 59 ]
	do
		echo $min
		(( min++ ))
	done
	min=$((1))
	(( hour++ ))
done
