#!/usr/bin/env bash
#Checks if file exist and print 'School file exists'
#Chechks if it does not exist and print 'School file does not exist'
#if exists check if empty print 'School file is empty'
#if nut empty print 'School file is not empty'
#if a regular file print 'School file is a regular file
if [ -e "School" ]; then
	echo "school file exists"
	if [ -s "school" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]; then
		echo "school file is a regular file"
	fi
else
	echo "scholl file does not exist"
fi
